version: '3'

services:
  app1:
    build: ./build

  app2:
    build: ./build
  
  app3:
    build: ./build

  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
      - app3

  db:
    image: mariadb
    ports:
    - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root_secret_password
    volumes:
      - ./database/mariadb-data:/var/lib/mysql
      - ./database/vaccination.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./backend/VacciNationAPI
    environment:
      DB_IP: db
      DB_NAME: vaccination
      DB_USER: root
      DB_PWD: root_secret_password
      DB_PORT: 3306
      SENDGRID_API_KEY: use_sendgrid_generated_api_key_here
    ports:
    - "5002:80"
    - "5000:5000"
    - "5001:5001"
