version: '3.1'

services:
  db:
    image: mariadb
    ports:
    - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root_secret_password
    volumes:
      - ./database/mariadb-data:/var/lib/mysql
      - ./database/vaccination.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./backend/VacciNationAPI
    environment:
      DB_IP: db
      DB_NAME: vaccination
      DB_USER: root
      DB_PWD: root_secret_password
      DB_PORT: 3306
      SENDGRID_API_KEY: key_here
    ports:
    - "5002:80"
    - "5000:5000"
    - "5001:5001"
  ui:
    build: ./frontend/mainapp
    ports:
    - "3000:3000"

